language: python
python:
    - "2.7"

install:
    - pip install -U https://github.com/platformio/platformio/archive/develop.zip

script:
    - platformio remote agent list
    - platformio remote device list
    - platformio remote run --target upload
